services:
  - type: web
    name: face-attendance-flask
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: flask run --host=0.0.0.0 --port=$PORT
    envVars:
      - key: FLASK_APP
        value: app.py
